// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: spec/v1/book.proto

package specv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Book gives the specs a message with rules, since lib cannot import the protos
// of a service.
type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Isbn          string                 `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_spec_v1_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_spec_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

// Broken carries a rule that only fails when protovalidate compiles it.
type Broken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broken) Reset() {
	*x = Broken{}
	mi := &file_spec_v1_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broken) ProtoMessage() {}

func (x *Broken) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broken.ProtoReflect.Descriptor instead.
func (*Broken) Descriptor() ([]byte, []int) {
	return file_spec_v1_book_proto_rawDescGZIP(), []int{1}
}

func (x *Broken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_spec_v1_book_proto protoreflect.FileDescriptor

const file_spec_v1_book_proto_rawDesc = "" +
	"\n" +
	"\x12spec/v1/book.proto\x12\aspec.v1\x1a\x1bbuf/validate/validate.proto\"O\n" +
	"\x04Book\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18?R\x05title\x12&\n" +
	"\x04isbn\x18\x02 \x01(\tB\x12\xbaH\x0fr\r2\v^[0-9]{13}$R\x04isbn\"=\n" +
	"\x06Broken\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:\x1f\xbaH\x1c\x1a\x1a\n" +
	"\x06broken\x1a\x10this.absent == 1BLZJgithub.com/quadrubo/golib/grpcinterceptor/validate/testdata/spec/v1;specv1b\x06proto3"

var (
	file_spec_v1_book_proto_rawDescOnce sync.Once
	file_spec_v1_book_proto_rawDescData []byte
)

func file_spec_v1_book_proto_rawDescGZIP() []byte {
	file_spec_v1_book_proto_rawDescOnce.Do(func() {
		file_spec_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_v1_book_proto_rawDesc), len(file_spec_v1_book_proto_rawDesc)))
	})
	return file_spec_v1_book_proto_rawDescData
}

var file_spec_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spec_v1_book_proto_goTypes = []any{
	(*Book)(nil),   // 0: spec.v1.Book
	(*Broken)(nil), // 1: spec.v1.Broken
}
var file_spec_v1_book_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spec_v1_book_proto_init() }
func file_spec_v1_book_proto_init() {
	if File_spec_v1_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_v1_book_proto_rawDesc), len(file_spec_v1_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_v1_book_proto_goTypes,
		DependencyIndexes: file_spec_v1_book_proto_depIdxs,
		MessageInfos:      file_spec_v1_book_proto_msgTypes,
	}.Build()
	File_spec_v1_book_proto = out.File
	file_spec_v1_book_proto_goTypes = nil
	file_spec_v1_book_proto_depIdxs = nil
}
